blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog_app.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace='blog_app')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/blog_app/urls.py
from django.urls import path

from .views import post_detail, post_list, post_comment
from .feeds import LatestPostsFeed

app_name = 'blog_app'

urlpatterns = [
    path('', post_list, name='posts'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail, name='post_detail'),
    path('post/<int:post_id>/comment/', post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed')
]

blog/blog_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """
    Менеджер для опубликованных постов.
    """

    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    """
    Модель поста блога.
    """

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date="publish")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_app:post_detail", args=[self.publish.year,
                                                     self.publish.month,
                                                     self.publish.day,
                                                     self.slug])


class Comment(models.Model):
    """
    Модель комментария.
    """

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created', ]
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий от {self.name} на {self.post}'

blog/blog_app/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    """
    Форма отправки постов по email.
    """
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """
    Форма написания коментария.
    """

    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

blog/blog_app/views.py
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.db.models import Count
from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm


# class PostList(ListView):
#     """
#     Отображение всех постов
#     """
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog_app/post/list.html"


def post_list(request, tag_slug=None):
    """
    Отображение всех постов.
    :param request:
    :return:
    """
    template = "blog_app/post/list.html"
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts_list = paginator.page(page_number)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)
    context = {"posts": posts_list,
               "tag": tag}
    return render(request, template, context=context)


def post_detail(request, year, month, day, post):
    """
    Отображение выбранного поста.
    :param request:
    :param id:
    :return:
    """
    template = "blog_app/post/detail.html"
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)

    # Формв комментариев
    form = CommentForm()

    # Список схожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {"post": post,
               "comments": comments,
               "form": form,
               "similar_posts": similar_posts}
    return render(request, template, context=context)


def post_share(request, post_id):
    """
    Представление отправки поста по email.
    :param request:
    :param post_id:
    :return:
    """
    template = "blog_app/post/share.html"
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
    else:
        form = EmailPostForm()
    context = {
        "post": post,
        "form": form
    }
    return render(request, template, context=context)


@require_POST
def post_comment(request, post_id):
    """
    Представление коментария в посте.
    :param request:
    :param post_id:
    :return:
    """
    template = "blog_app/post/comment.html"
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        "post": post,
        "form": form,
        "comment": comment
    }
    return render(request, template, context=context)

blog/templates/blog_app/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog_app.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>
            Это мой блог.
            Я написал {% total_posts %}.
        </p>
        <p>
            <a href="{% url 'blog_app:post_feed' %}">RSS feed</a>
        </p>
        <h3>Новые посты:</h3>
        {% show_latest_posts 3 %}
        <h3>Самые обсуждаемые:</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog_app/post/comment.html
{% extends "blog_app/base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Вернуться в пост</a></p>
  {% else %}
    {% include "blog_app/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blog/templates/blog_app/post/detail.html
{% extends 'blog_app/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Опубликовано {{ post.publish }} {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Схожих постов пока нет
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} от {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Здесь нет комментариев.</p>
    {% endfor %}
    {% include "blog_app/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog_app/post/includes/comment_form.html
<h2>Добавить новый комментарий</h2>
<form action="{% url 'blog_app:post_comment' post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Добавить комментарий"></p>
</form>

blog/templates/blog_app/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog_app/post/list.html
{% extends 'blog_app/base.html' %}
{% load blog_tags %}

{% block title %}My blog{% endblock %}

{% block content %}
    <h1>My blog</h1>
    {% if tag %}
        <h2>Посты с тегом {{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">Тэги:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog_app:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %},
            {% endif %}
        {% endfor %}
        </p>
        <p class="date">
            Опубликовано {{ post.publish }} {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"> Следующая</a>
        {% endif %}
    </span>
</div>